name:               robin
version:            0.1.0.0
synopsis:           A programming language with lambdas and binary trees
homepage:           www.github.com/alexj136/robin
license:            AllRightsReserved
license-file:       LICENSE.md
author:             Alex Jeffery
maintainer:         A.P.Jeffery@sussex.ac.uk
category:           Language
build-type:         Simple
cabal-version:      >=1.10
executable robin
  main-is:              Main.hs
  build-depends:        base,
                        containers,
                        array,
                        mtl,
                        robin
  hs-source-dirs:       src/exec
  default-language:     Haskell2010
  ghc-options:          -fwarn-incomplete-patterns
library
  build-tools:          alex,
                        happy
  default-language:     Haskell2010
  ghc-options:          -fwarn-incomplete-patterns
  hs-source-dirs:       src/lib
  build-depends:        base,
                        containers,
                        array,
                        mtl
  exposed-modules:      Util,
                        Lexer,
                        Parser,
                        SugarSyntax,
                        DeBruijnSyntax,
                        Types,
                        TypeCheck,
                        Interpreter,
                        CodeGen
Test-Suite robin-testsuite
  default-language:     Haskell2010
  ghc-options:          -fwarn-incomplete-patterns
  hs-source-dirs:       src/test
  build-depends:        base,
                        containers,
                        array,
                        mtl,
                        HUnit,
                        robin
  other-modules:        TestSugarSyntax,
  -- TestParser,
                        TestTypeCheck
  type:                 exitcode-stdio-1.0
  main-is:              TestMain.hs
